name: Build with MinGW-W64 + Clang

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ["i686", "x86_64"]

    steps:
      - uses: KOLANICH-GHActions/typical-MinGW-w64-cross-build@master
        with:
          llvm_version: ${{matrix.llvm_version}}
